[package]
name = "openapi-hackday-gen"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.15", features = ["derive"] }
okapi = "0.4.0"
serde = { version = "1.0.140", features = ["derive"] }
serde_yaml = "0.9.0"
